import type { DeckConfig, DeckPlan, DeckSection, DeckSlide, KnowledgeCard } from './schema';

export const OPENATLAS_INVESTOR_DEMO_PROMPT = 'InsightLab 数智员工融资汇报，面向投资人，18 分钟，数据图表丰富，突出市场机会、产品飞轮、商业模式和融资用途';

export function buildOpenAtlasInvestorDemo(): { config: DeckConfig; plan: DeckPlan } {
  const demoConfig: DeckConfig = {
    topic: 'InsightLab 数智员工融资汇报',
    useCase: 'roadshow',
    aspectRatio: '16:9',
    styleKey: 'tech_launch',
    audience: '投资人 / 产业资本 / 企业客户',
    durationMinutes: 18,
    pageCount: 12,
    density: 'dense',
    chartLevel: 'rich',
    speakerNotes: true,
  };
  const sections: DeckSection[] = [
    { id: 's-open', title: '机会', purpose: '用宏观转折和客户痛点建立融资叙事。' },
    { id: 's-product', title: '产品', purpose: '说明 InsightLab 如何把 Agent 从问答变成交付岗位。' },
    { id: 's-business', title: '商业', purpose: '展示增长模型、收入假设和投资回报。' },
    { id: 's-close', title: '融资', purpose: '明确资金用途、里程碑和行动请求。' },
  ];
  const knowledge: KnowledgeCard[] = [
    {
      id: 'k-demo-note',
      title: '样例数据说明',
      source: '产品演示口径',
      detail: '本样例中的市场、转化、收入和成本数字均为融资路演演示口径，用于检验富图表渲染效果，正式对外材料需替换为真实经营数据。',
      status: 'assumption',
    },
    {
      id: 'k-market',
      title: 'AI Agent 市场窗口',
      source: '待接入外部研究',
      detail: '建议补充企业 AI 软件预算、Agent 平台渗透率、知识工作自动化趋势等权威研究来源。',
      status: 'missing',
    },
    {
      id: 'k-product',
      title: 'InsightLab 产品能力',
      source: '产品路线图',
      detail: '覆盖数智员工、A2UI、AIPPT、公文写作、合同审核、创意白板和知识检索等场景能力。',
      status: 'ready',
    },
    {
      id: 'k-finance',
      title: '商业模型假设',
      source: '融资模型样例',
      detail: 'ARR、毛利、CAC 回收期、净收入留存等数字为样例假设，正式版本需要替换为财务模型。',
      status: 'assumption',
    },
  ];
  const slides: DeckSlide[] = [
    {
      id: 'demo-slide-1',
      sectionId: 's-open',
      index: 1,
      title: 'InsightLab 数智员工平台',
      headline: '让 AI 从工具走向岗位，从对话走向可交付业务结果',
      bullets: ['A2UI 把 Agent 判断变成卡片、表单和画布节点。', '数智员工沉淀技能、知识、流程和审计链路。', '融资用于产品化、行业验证和渠道增长。'],
      visual: '深色科技封面 + 机会宣言',
      layout: 'cover',
      knowledgeIds: ['k-demo-note', 'k-product'],
      status: 'confirmed',
      speakerNotes: '先用一句话定义 InsightLab：不是聊天机器人，而是企业可管理、可交付、可审计的数智员工平台。',
      designIntent: '大标题建立品类心智，右侧 Topic 卡强调投资人路演属性。',
      renderHints: ['emphasis=AI 从工具走向岗位', 'callout=融资路演样例数据'],
      evidenceRole: '正式路演需补充真实公司介绍、融资轮次和核心团队信息。',
    },
    {
      id: 'demo-slide-2',
      sectionId: 's-open',
      index: 2,
      title: '为什么是现在',
      headline: '企业 AI 预算进入落地期，Agent 正从试点转向岗位化部署',
      bullets: ['AI 应用试点从 Copilot 走向可交付流程。', '企业更关注合规、审计、知识沉淀和 ROI。', 'InsightLab 切入“人机协同交付”这一中间层。'],
      visual: '左侧采用 Agent 落地成熟度折线，右侧三张窗口期指标卡',
      layout: 'metrics',
      knowledgeIds: ['k-market', 'k-demo-note'],
      status: 'confirmed',
      speakerNotes: '强调窗口不是模型能力本身，而是企业需要把模型能力接进组织流程、权限和交付物。',
      designIntent: '趋势折线承载时间窗口，指标卡承载投资判断。',
      renderHints: ['chart=line', 'emphasis=从试点到岗位化'],
      visualSpec: {
        type: 'combo_metrics',
        title: 'Agent 落地成熟度',
        chart: {
          kind: 'line',
          labels: ['2024H1', '2024H2', '2025H1', '2025H2', '2026H1'],
          series: [{ name: '企业 Agent 落地成熟度', values: [18, 27, 41, 58, 73], unit: '%' }],
          source: '演示假设，正式材料需替换为研究数据。',
        },
        metrics: [
          { label: '试点转生产', value: '2.6x', detail: '从单点试验走向流程级上线' },
          { label: '预算优先级', value: 'Top 3', detail: 'CIO 关注自动化和知识效率' },
          { label: '落地缺口', value: '4类', detail: '权限、流程、审计、交付物' },
        ],
      },
      evidenceRole: '需要补充行业研究或目标客户访谈，验证企业 Agent 部署窗口。',
    },
    {
      id: 'demo-slide-3',
      sectionId: 's-open',
      index: 3,
      title: '客户正在为低质量自动化付费',
      headline: '传统 AI 工具能回答问题，但难以稳定完成岗位任务',
      bullets: ['知识散落导致重复问答和上下文丢失。', '流程无法审计，结果难以交接给业务系统。', '复杂交付物仍依赖人工补字段、改格式、做复核。'],
      visual: '四类成本柱状图：返工、等待、合规、知识流失',
      layout: 'metrics',
      knowledgeIds: ['k-market', 'k-demo-note'],
      status: 'confirmed',
      speakerNotes: '把痛点从“AI 不够聪明”转为“企业组织无法消费模型能力”。',
      designIntent: '柱状图让投资人看到痛点可量化，右侧指标卡显示成本类型。',
      renderHints: ['chart=bar', 'emphasis=业务损耗'],
      visualSpec: {
        type: 'bar',
        title: '知识工作损耗结构',
        chart: {
          kind: 'bar',
          labels: ['重复问答', '人工返工', '审批等待', '合规复核', '资料查找'],
          series: [{ name: '损耗强度', values: [62, 78, 45, 56, 68], unit: '分' }],
          source: '演示假设，用于表达痛点结构。',
        },
      },
      evidenceRole: '正式版本应接入客户访谈、任务日志或行业效率损耗报告。',
    },
    {
      id: 'demo-slide-4',
      sectionId: 's-product',
      index: 4,
      title: 'InsightLab 产品架构',
      headline: '用感知、记忆、规划、执行四层，把 Agent 变成可运营的岗位',
      bullets: ['感知层接入对话、文件、网页和业务系统。', '记忆层沉淀企业知识、技能和员工画像。', '规划与执行层生成 UI、调用工具并形成交付物。'],
      visual: '四层垂直架构图：感知 → 记忆 → 规划 → 执行',
      layout: 'diagram',
      knowledgeIds: ['k-product'],
      status: 'confirmed',
      speakerNotes: '突出 InsightLab 不是单一模型封装，而是面向企业交付闭环的平台层。',
      designIntent: '分层架构帮助投资人理解产品边界和可扩展性。',
      renderHints: ['flow=layered', 'callout=可审计闭环'],
      visualSpec: {
        type: 'architecture',
        title: '数智员工四层架构',
        layers: [
          { label: '感知层', detail: '对话、文件、网页、系统事件、多模态输入' },
          { label: '记忆层', detail: '企业知识库、员工技能、历史任务、向量检索' },
          { label: '规划层', detail: '任务拆解、A2UI Schema、组件注册表、状态机' },
          { label: '执行层', detail: '工具调用、文档/PPT/审核交付物、审计日志' },
        ],
        callouts: ['人机确认', '权限控制', '过程可追溯'],
      },
      evidenceRole: '可用产品架构图、组件清单和真实任务日志支撑。',
    },
    {
      id: 'demo-slide-5',
      sectionId: 's-product',
      index: 5,
      title: '产品飞轮',
      headline: '每一次任务交付都会反哺技能、知识和界面生成能力',
      bullets: ['用户需求触发 Agent 规划，生成可确认 UI。', '人工确认后的字段、修改和资料成为组织记忆。', '高频场景沉淀为技能包，降低下一次交付成本。'],
      visual: '闭环流程：需求 → A2UI → 交付物 → 反馈 → 技能沉淀',
      layout: 'process',
      knowledgeIds: ['k-product'],
      status: 'confirmed',
      speakerNotes: '讲清楚壁垒不是单次生成质量，而是持续使用带来的组织级学习曲线。',
      designIntent: '流程页呈现复利逻辑，避免只讲功能清单。',
      renderHints: ['flow=loop', 'emphasis=越用越懂企业'],
      evidenceRole: '正式版本可加入客户任务量、复用率和技能沉淀数量。',
    },
    {
      id: 'demo-slide-6',
      sectionId: 's-product',
      index: 6,
      title: '三类产品能力对比',
      headline: 'InsightLab 的差异在于“可交付、可审计、可运营”',
      bullets: ['通用 Agent 强在回答，但缺少组织级记忆与交付流程。', 'RPA 强在固定流程，但难以处理开放语义任务。', 'InsightLab 把模型、流程、UI 和知识连成闭环。'],
      visual: '三列对比矩阵：InsightLab vs 通用 Agent 平台 vs RPA 工具',
      layout: 'compare',
      knowledgeIds: ['k-product', 'k-market'],
      status: 'confirmed',
      speakerNotes: '把竞品对比放在能力维度，而不是品牌名攻击。',
      designIntent: '用矩阵一眼呈现能力等级和护城河来源。',
      renderHints: ['matrixTitle=能力差异矩阵', 'emphasis=InsightLab 全链路闭环'],
      visualSpec: {
        type: 'matrix',
        title: '能力差异矩阵',
        description: '色块深浅表示能力完整度。',
        columns: [
          { label: 'InsightLab', score: 'high', items: ['企业级记忆', '多 Agent 协同', 'A2UI 确认流', '交付物生成', '审计日志'] },
          { label: '通用 Agent 平台', score: 'medium', items: ['模型能力强', '插件生态', '企业记忆弱', '交付流程弱', '审计链路不足'] },
          { label: 'RPA / 低代码', score: 'low', items: ['固定流程稳定', '开放语义弱', '知识沉淀弱', '多模态弱', '变更成本高'] },
        ],
      },
      evidenceRole: '建议补充竞品公开资料、客户反馈和功能矩阵验证。',
    },
    {
      id: 'demo-slide-7',
      sectionId: 's-business',
      index: 7,
      title: '场景组合与收入入口',
      headline: '先从高频交付物切入，再扩展为数智员工平台订阅',
      bullets: ['公文写作、合同审核、AIPPT 是易感知价值的高频入口。', '创意白板和知识检索沉淀上下文，提升复用率。', '数智员工按岗位、技能包和组织规模扩展付费。'],
      visual: '收入入口柱状图 + 右侧指标卡',
      layout: 'metrics',
      knowledgeIds: ['k-finance', 'k-product'],
      status: 'confirmed',
      speakerNotes: '说明为什么不从大而全平台卖起，而是用高频场景建立使用习惯和数据飞轮。',
      designIntent: '柱状图展示场景优先级，指标卡承接商业化指标。',
      renderHints: ['chart=bar', 'emphasis=高频入口'],
      visualSpec: {
        type: 'bar',
        title: '场景收入优先级',
        chart: {
          kind: 'bar',
          labels: ['公文写作', '合同审核', 'AIPPT', '创意白板', '知识检索'],
          series: [{ name: '商业化优先级', values: [86, 82, 78, 64, 58], unit: '分' }],
          source: '演示假设，正式版本需补充真实转化。',
        },
      },
      evidenceRole: '建议补充各场景活跃、转化率、留存和付费意愿数据。',
    },
    {
      id: 'demo-slide-8',
      sectionId: 's-business',
      index: 8,
      title: '增长模型',
      headline: '从试点客户到组织扩张，形成 ARR 与 NRR 双轮驱动',
      bullets: ['试点从 2-3 个高频岗位切入。', '扩张来自部门复制、技能包增加和员工席位提升。', '客户成功指标聚焦激活率、复用率和交付物质量。'],
      visual: '近 6 个季度 ARR 折线 + 右侧三张 SaaS 指标卡',
      layout: 'metrics',
      knowledgeIds: ['k-finance', 'k-demo-note'],
      status: 'confirmed',
      speakerNotes: '这页用样例模型讲增长逻辑，真实路演时替换成公司财务模型。',
      designIntent: '折线图讲趋势，指标卡讲 SaaS 质量。',
      renderHints: ['chart=line', 'emphasis=ARR 与 NRR 双轮'],
      visualSpec: {
        type: 'combo_metrics',
        title: 'ARR 增长样例模型',
        chart: {
          kind: 'line',
          labels: ['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6'],
          series: [{ name: 'ARR', values: [80, 135, 230, 390, 640, 980], unit: '万' }],
          source: '演示假设。',
        },
        metrics: [
          { label: 'NRR', value: '128%', detail: '组织扩张与技能包增购' },
          { label: '毛利率', value: '72%', detail: '模型与交付成本优化后目标' },
          { label: 'CAC 回收', value: '7月', detail: '渠道与客户成功协同假设' },
        ],
      },
      evidenceRole: '正式版本需替换为财务模型、客户队列和真实收入数据。',
    },
    {
      id: 'demo-slide-9',
      sectionId: 's-business',
      index: 9,
      title: '单位经济模型',
      headline: '用平台化交付降低边际成本，让客户成功成为增长引擎',
      bullets: ['技能复用率越高，交付成本越低。', 'A2UI 确认流降低返工，提升首次交付通过率。', '知识沉淀提升续费与部门扩张概率。'],
      visual: '单位经济指标卡：毛利率、复用率、交付通过率、续费率',
      layout: 'metrics',
      knowledgeIds: ['k-finance', 'k-demo-note'],
      status: 'confirmed',
      speakerNotes: '强调 InsightLab 不是项目制外包，而是可复用、可规模化的软件平台。',
      designIntent: '数字卡片突出经营杠杆。',
      renderHints: ['chart=scorecard', 'emphasis=经营杠杆'],
      visualSpec: {
        type: 'scorecard',
        metrics: [
          { label: '技能复用率', value: '61%', detail: '同类任务复用已有技能包' },
          { label: '首稿通过率', value: '74%', detail: 'A2UI 确认后减少返工' },
          { label: '目标毛利率', value: '72%', detail: '平台化交付后的目标区间' },
          { label: '目标续费率', value: '92%', detail: '组织记忆增强粘性' },
        ],
      },
      evidenceRole: '需用产品日志和客户续费数据验证。',
    },
    {
      id: 'demo-slide-10',
      sectionId: 's-close',
      index: 10,
      title: '融资用途',
      headline: '资金优先投入产品化、行业样板和可复制增长',
      bullets: ['45% 用于平台工程、A2UI renderer 和企业安全。', '35% 用于标杆行业样板、客户成功和渠道。', '20% 用于模型成本优化、运营和合规认证。'],
      visual: '融资用途柱状图',
      layout: 'metrics',
      knowledgeIds: ['k-finance'],
      status: 'confirmed',
      speakerNotes: '让投资人看到钱会买来什么确定性，而不是泛泛扩张。',
      designIntent: '柱状图呈现资金分配结构。',
      renderHints: ['chart=bar', 'emphasis=资金买确定性'],
      visualSpec: {
        type: 'bar',
        title: '资金用途结构',
        chart: {
          kind: 'bar',
          labels: ['产品工程', '行业样板', '客户成功', '模型成本', '合规运营'],
          series: [{ name: '资金占比', values: [45, 22, 13, 12, 8], unit: '%' }],
          source: '演示假设。',
        },
      },
      evidenceRole: '正式版本需对应融资金额、招聘计划和产品路线图。',
    },
    {
      id: 'demo-slide-11',
      sectionId: 's-close',
      index: 11,
      title: '18 个月里程碑',
      headline: '用三阶段把产品、客户和收入证明做扎实',
      bullets: ['0-6 月：打磨 A2UI renderer，完成 3 个标杆行业样板。', '6-12 月：数智员工技能市场上线，形成可复制交付包。', '12-18 月：规模化渠道合作，验证 ARR 与 NRR 模型。'],
      visual: '三阶段路线图',
      layout: 'timeline',
      knowledgeIds: ['k-finance', 'k-product'],
      status: 'confirmed',
      speakerNotes: '把融资用途和里程碑绑定，降低投资人对执行不确定性的担心。',
      designIntent: '时间线展示资金使用后的阶段成果。',
      renderHints: ['flow=timeline', 'emphasis=18个月验证'],
      evidenceRole: '需要结合产品排期、客户 pipeline 和团队招聘计划。',
    },
    {
      id: 'demo-slide-12',
      sectionId: 's-close',
      index: 12,
      title: '本轮希望验证的三件事',
      headline: '把 InsightLab 做成企业数智员工的操作系统',
      bullets: ['完成核心融资，与产业资源共建标杆客户。', '优先验证 A2UI + 数智员工在高频交付物场景的留存。', '形成可复制的行业技能包和客户成功方法论。'],
      visual: '行动清单 + 结尾金句',
      layout: 'quote',
      knowledgeIds: ['k-demo-note', 'k-product'],
      status: 'confirmed',
      speakerNotes: '结尾回到品类愿景和明确行动请求。',
      designIntent: '用一句强记忆点结束，同时给出具体 next step。',
      renderHints: ['callout=企业数智员工操作系统', 'emphasis=融资行动'],
      evidenceRole: '正式版本需要补充融资金额、合作方式和联系人。',
    },
  ];
  return {
    config: demoConfig,
    plan: {
      title: 'InsightLab 数智员工融资汇报｜富图表样例',
      sections,
      slides,
      knowledge,
      generatedAt: new Date().toISOString(),
    },
  };
}

export const GENERIC_OPERATIONS_DEMO_PROMPT = '生成一份企业知识库运营升级汇报，面向管理层，15 分钟，包含效率指标、方案架构、实施路线和风险控制';

export function buildGenericOperationsDemo(): { config: DeckConfig; plan: DeckPlan } {
  const demoConfig: DeckConfig = {
    topic: '企业知识库运营升级汇报',
    useCase: 'report',
    aspectRatio: '16:9',
    styleKey: 'executive_blue',
    audience: '管理层 / 业务负责人 / IT 负责人',
    durationMinutes: 15,
    pageCount: 8,
    density: 'standard',
    chartLevel: 'rich',
    speakerNotes: true,
  };
  const sections: DeckSection[] = [
    { id: 's-context', title: '现状', purpose: '说明知识管理问题和改造必要性。' },
    { id: 's-solution', title: '方案', purpose: '展示目标架构、运营机制和能力差异。' },
    { id: 's-plan', title: '落地', purpose: '明确实施路线、指标和风险控制。' },
  ];
  const knowledge: KnowledgeCard[] = [
    {
      id: 'k-ops-note',
      title: '样例数据说明',
      source: '中性演示口径',
      detail: '本样例使用匿名化、估算型运营数据，仅用于验证 AIPPT 富图表渲染和可编辑 schema。',
      status: 'assumption',
    },
    {
      id: 'k-current',
      title: '知识库现状访谈',
      source: '内部访谈纪要示例',
      detail: '业务人员反馈资料查找时间长、版本分散、问答口径不一致。',
      status: 'ready',
    },
    {
      id: 'k-target',
      title: '运营目标',
      source: '项目目标假设',
      detail: '目标是在 12 周内建立统一知识入口、责任机制和质量指标。',
      status: 'assumption',
    },
  ];
  const slides: DeckSlide[] = [
    {
      id: 'generic-slide-1',
      sectionId: 's-context',
      index: 1,
      title: '企业知识库运营升级',
      headline: '把分散资料变成可运营、可追踪、可复用的组织知识资产',
      bullets: ['统一入口减少重复查找。', '责任机制提升内容新鲜度。', '指标体系让知识运营可持续。'],
      visual: '管理层汇报封面 + 目标摘要',
      layout: 'cover',
      knowledgeIds: ['k-ops-note', 'k-target'],
      status: 'confirmed',
      speakerNotes: '先把知识库升级定义为运营体系建设，而不是单纯换工具。',
      designIntent: '正式汇报风格，突出目标和收益。',
      renderHints: ['emphasis=组织知识资产'],
    },
    {
      id: 'generic-slide-2',
      sectionId: 's-context',
      index: 2,
      title: '当前痛点量化',
      headline: '查找慢、版本乱、复用低，是知识库低效的三类核心损耗',
      bullets: ['资料平均查找耗时偏高。', '历史版本与最新口径混杂。', '高频问题仍依赖人工重复解释。'],
      visual: '柱状图 + 指标卡',
      layout: 'metrics',
      knowledgeIds: ['k-current', 'k-ops-note'],
      status: 'confirmed',
      speakerNotes: '用可量化痛点建立改造必要性，正式汇报应替换为真实日志和问卷数据。',
      designIntent: '左侧柱状图表达损耗结构，右侧指标卡承接管理层关注。',
      renderHints: ['chart=bar', 'emphasis=效率损耗'],
      visualSpec: {
        type: 'combo_metrics',
        title: '知识使用损耗结构',
        chart: {
          kind: 'bar',
          labels: ['查找资料', '确认版本', '重复问答', '跨部门同步'],
          series: [{ name: '平均耗时', values: [34, 22, 18, 27], unit: '分钟/次' }],
          source: '中性演示口径，基于访谈样例估算。',
          methodology: '按典型知识工作场景估算单次损耗，不代表真实客户数据。',
          estimated: true,
        },
        metrics: [
          { label: '知识命中率', value: '52%', detail: '用户首次搜索可用结果占比' },
          { label: '重复问题', value: '38%', detail: '近月问答中重复出现比例' },
          { label: '内容过期', value: '21%', detail: '待复核或责任人缺失内容占比' },
        ],
      },
      evidenceRole: '正式版本建议接入搜索日志、工单和内容审计结果。',
    },
    {
      id: 'generic-slide-3',
      sectionId: 's-context',
      index: 3,
      title: '目标指标',
      headline: '12 周内把知识库从“资料仓库”升级为“运营系统”',
      bullets: ['提升搜索命中率和首问解决率。', '降低重复问答和人工同步时间。', '建立内容责任人与复核节奏。'],
      visual: '目标指标卡',
      layout: 'metrics',
      knowledgeIds: ['k-target', 'k-ops-note'],
      status: 'confirmed',
      speakerNotes: '目标不追求一次性完美，而是先建立指标闭环。',
      designIntent: '指标卡适合管理层快速判断项目收益。',
      renderHints: ['chart=scorecard', 'emphasis=12周目标'],
      visualSpec: {
        type: 'scorecard',
        metrics: [
          { label: '搜索命中率', value: '75%', detail: '12 周目标值' },
          { label: '首问解决率', value: '68%', detail: '自助问答可解决比例' },
          { label: '重复问答下降', value: '30%', detail: '人工重复解释减少幅度' },
          { label: '内容复核覆盖', value: '90%', detail: '重点知识卡复核覆盖率' },
        ],
      },
      evidenceRole: '需要项目基线数据和上线后统计报表验证。',
    },
    {
      id: 'generic-slide-4',
      sectionId: 's-solution',
      index: 4,
      title: '目标架构',
      headline: '用采集、治理、检索、运营四层把知识流动起来',
      bullets: ['采集层统一接入文档、问答、系统记录。', '治理层负责标签、版本、权限和责任人。', '检索与运营层形成反馈闭环。'],
      visual: '四层知识运营架构图',
      layout: 'diagram',
      knowledgeIds: ['k-target'],
      status: 'confirmed',
      speakerNotes: '强调架构不是系统堆叠，而是每层都有运营责任。',
      designIntent: '分层图帮助管理层理解建设范围。',
      renderHints: ['flow=layered', 'callout=闭环运营'],
      visualSpec: {
        type: 'architecture',
        title: '知识运营四层架构',
        layers: [
          { label: '采集层', detail: '文档、问答、会议纪要、业务系统记录' },
          { label: '治理层', detail: '标签体系、版本管理、权限、责任人' },
          { label: '检索层', detail: '关键词检索、语义检索、推荐和引用' },
          { label: '运营层', detail: '质量评分、复核节奏、使用反馈、仪表盘' },
        ],
        callouts: ['责任到人', '来源可追踪', '持续复核'],
      },
    },
    {
      id: 'generic-slide-5',
      sectionId: 's-solution',
      index: 5,
      title: '三类方案对比',
      headline: '从“建库”转向“运营”，才能持续提升知识复用率',
      bullets: ['普通网盘解决存放，不解决使用和更新。', '传统知识库解决归档，但运营指标弱。', '知识运营系统强调责任、反馈和数据闭环。'],
      visual: '三列方案能力矩阵',
      layout: 'compare',
      knowledgeIds: ['k-current', 'k-target'],
      status: 'confirmed',
      speakerNotes: '避免只做工具采购，强调运营机制是差异点。',
      designIntent: '矩阵快速说明为什么需要升级。',
      renderHints: ['matrixTitle=方案能力矩阵'],
      visualSpec: {
        type: 'matrix',
        title: '方案能力矩阵',
        description: '色块强弱表示对运营目标的支撑程度。',
        columns: [
          { label: '网盘/共享目录', score: 'low', items: ['存储方便', '检索弱', '责任弱', '版本混乱'] },
          { label: '传统知识库', score: 'medium', items: ['结构化归档', '权限管理', '运营指标弱', '反馈闭环弱'] },
          { label: '知识运营系统', score: 'high', items: ['语义检索', '责任到人', '质量评分', '数据闭环'] },
        ],
      },
    },
    {
      id: 'generic-slide-6',
      sectionId: 's-solution',
      index: 6,
      title: '运营闭环',
      headline: '用“使用数据 -> 质量复核 -> 内容更新 -> 再推荐”形成持续改进',
      bullets: ['记录搜索、点击、引用和未命中问题。', '每周复核低分内容和高频未命中。', '更新后的内容进入推荐和问答链路。'],
      visual: '四步闭环流程',
      layout: 'process',
      knowledgeIds: ['k-target'],
      status: 'confirmed',
      speakerNotes: '流程页用于说明上线后如何长期运营。',
      designIntent: '闭环流程强化可持续，而非一次性迁移。',
      renderHints: ['flow=loop', 'emphasis=持续改进'],
    },
    {
      id: 'generic-slide-7',
      sectionId: 's-plan',
      index: 7,
      title: '12 周实施路线',
      headline: '先建立核心知识域和指标闭环，再扩展到全组织',
      bullets: ['第 1-2 周：梳理知识域、责任人和基线指标。', '第 3-6 周：迁移重点内容并完成标签治理。', '第 7-12 周：上线运营仪表盘和复核机制。'],
      visual: '三阶段实施时间线',
      layout: 'timeline',
      knowledgeIds: ['k-target'],
      status: 'confirmed',
      speakerNotes: '路线图要把人、内容和指标同步安排。',
      designIntent: '时间线帮助管理层判断资源投入节奏。',
      renderHints: ['flow=timeline', 'emphasis=12周落地'],
    },
    {
      id: 'generic-slide-8',
      sectionId: 's-plan',
      index: 8,
      title: '风险与决策请求',
      headline: '本项目成功的关键不是系统上线，而是责任机制和运营节奏落地',
      bullets: ['确认业务负责人和内容责任人。', '允许接入搜索日志和知识使用数据。', '以 12 周为周期复盘指标并决定扩展范围。'],
      visual: '行动清单',
      layout: 'checklist',
      knowledgeIds: ['k-target', 'k-ops-note'],
      status: 'confirmed',
      speakerNotes: '结尾明确需要管理层拍板的事项。',
      designIntent: '用行动清单收束决策。',
      renderHints: ['callout=责任机制优先'],
      evidenceRole: '正式版本需要确认数据接入权限、内容责任人和项目排期。',
    },
  ];
  return {
    config: demoConfig,
    plan: {
      title: '企业知识库运营升级汇报｜中性样例',
      sections,
      slides,
      knowledge,
      generatedAt: new Date().toISOString(),
    },
  };
}
